on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: Windows Pipeline

jobs:
  build:
    permissions: write-all

    name: Create Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Clone The Code
        run: git clone https://github.com/jetblacksalvation/OOGL-Cmake.git
      - name: Configure CMake
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
